### ISSUE TITLE
React 15.5 warning

### ISSUE THREAD

**Issue by ryuken** [chadly/react-bs-notifier#23]
warning.js:36 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

**Comment by chadly** [comment]
fixed in v4.3.1

**Comment by calimaborges** [comment]
@chadly sorry, my pull request didn't solve the problem entirely. `react-jss` dependency still threw the warning. I just created another pull request #25 upgrading the dependency.

The docs are still throwing the warning though. Due to `react-remarkable` `createClass` and `component-playground` `propTypes`.
